export const dogBreeds = [
  { label: "Labrador Retriever" },
  { label: "German Shepherd" },
  { label: "Golden Retriever" },
  { label: "Bulldog" },
  { label: "Poodle" },
  { label: "Beagle" },
  { label: "Rottweiler" },
  { label: "Dachshund" },
  { label: "Yorkshire Terrier" },
  { label: "Boxer" },
  { label: "Siberian Husky" },
  { label: "Shih Tzu" },
  { label: "Doberman Pinscher" },
  { label: "Chihuahua" },
  { label: "Great Dane" },
  { label: "Pug" },
  { label: "Australian Shepherd" },
  { label: "Cavalier King Charles Spaniel" },
  { label: "Miniature Schnauzer" },
  { label: "Pembroke Welsh Corgi" },
  { label: "Border Collie" },
  { label: "Basset Hound" },
  { label: "Akita" },
  { label: "Mastiff" },
  { label: "Pit Bull Terrier" },
  { label: "Bernese Mountain Dog" },
  { label: "Cocker Spaniel" },
  { label: "Boston Terrier" },
  { label: "French Bulldog" },
  { label: "Alaskan Malamute" },
  { label: "Havanese" },
  { label: "Maltese" },
  { label: "Sheltie" },
  { label: "Vizsla" },
  { label: "Weimaraner" },
  { label: "Irish Setter" },
  { label: "Bichon Frise" },
  { label: "Papillon" },
  { label: "Newfoundland" },
  { label: "Shiba Inu" },
  { label: "English Springer Spaniel" },
  { label: "Whippet" },
  { label: "Bloodhound" },
  { label: "Pointer" },
  { label: "Afghan Hound" },
  { label: "Airedale Terrier" },
  { label: "American Eskimo Dog" },
  { label: "American Foxhound" },
  { label: "Australian Cattle Dog" },
  { label: "Borzoi" },
  { label: "Bull Terrier" },
  { label: "Cardigan Welsh Corgi" },
  { label: "Chow Chow" },
  { label: "Dalmatian" },
  { label: "Great Pyrenees" },
  { label: "Keeshond" },
  { label: "Lhasa Apso" },
  { label: "Old English Sheepdog" },
  { label: "Pekingese" },
  { label: "Samoyed" },
  { label: "Scottish Terrier" },
  { label: "Soft Coated Wheaten Terrier" },
  { label: "St. Bernard" },
  { label: "Standard Schnauzer" },
  { label: "Toy Poodle" },
  { label: "Welsh Terrier" },
  { label: "West Highland White Terrier" },
  { label: "Wirehaired Pointing Griffon" },
  { label: "Xoloitzcuintli" },
];

export const catBreeds = [
  { label: "Abyssinian" },
  { label: "American Bobtail" },
  { label: "American Curl" },
  { label: "American Shorthair" },
  { label: "American Wirehair" },
  { label: "Balinese" },
  { label: "Bengal" },
  { label: "Birman" },
  { label: "Bombay" },
  { label: "British Longhair" },
  { label: "British Shorthair" },
  { label: "Burmese" },
  { label: "Burmilla" },
  { label: "Chartreux" },
  { label: "Chausie" },
  { label: "Cornish Rex" },
  { label: "Cymric" },
  { label: "Devon Rex" },
  { label: "Egyptian Mau" },
  { label: "European Burmese" },
  { label: "Exotic Shorthair" },
  { label: "Havana Brown" },
  { label: "Himalayan" },
  { label: "Japanese Bobtail" },
  { label: "Javanese" },
  { label: "Khao Manee" },
  { label: "Korat" },
  { label: "LaPerm" },
  { label: "Lykoi" },
  { label: "Maine Coon" },
  { label: "Manx" },
  { label: "Munchkin" },
  { label: "Nebelung" },
  { label: "Norwegian Forest Cat" },
  { label: "Ocicat" },
  { label: "Oriental Longhair" },
  { label: "Oriental Shorthair" },
  { label: "Persian" },
  { label: "Pixie-Bob" },
  { label: "Ragamuffin" },
  { label: "Ragdoll" },
  { label: "Russian Blue" },
  { label: "Savannah" },
  { label: "Scottish Fold" },
  { label: "Selkirk Rex" },
  { label: "Siamese" },
  { label: "Siberian" },
  { label: "Singapura" },
  { label: "Snowshoe" },
  { label: "Somali" },
  { label: "Sphynx" },
  { label: "Tonkinese" },
  { label: "Toyger" },
  { label: "Turkish Angora" },
  { label: "Turkish Van" },
];
